// aegis-client/src/app/register/page.tsx
'use client'
import { useState } from 'react';

export default function RegisterPage() {
  const [formData, setFormData] = useState({
    username: "",
    password: ""
  });

  return (
    <div className="min-w-full h-full flex items-center justify-center">
      <div className="p-8 ring-2 ring-rose-700 rounded-lg shadow-md">
        <h1 className="text-2xl font-bold mb-6 text-center text-rose-700">Register</h1>
        <form >
          <div className="mb-4">
            <label className="block text-rose-700 text-sm font-bold mb-2">
              Username
            </label>
            <input
              type="text"
              value={formData.username}
              name='username'
              onChange={(e) => setFormData({ ...formData, username: e.target.value })}
              className="w-full px-3 py-2 border border-rose-700 rounded focus:outline-none focus:ring-2 focus:ring-rose-700"
              required
            />
          </div>
          <div className="mb-6">
            <label className="block text-rose-700 text-sm font-bold mb-2">
              Password
            </label>
            <input
              type="password"
              value={formData.password}
              name='password'
              onChange={(e) => setFormData({ ...formData, password: e.target.value })}
              className="w-full px-3 py-2 border border-rose-700 rounded focus:outline-none focus:ring-2 focus:ring-rose-700"
              required
            />
          </div>
          <button
            type="submit"
            className="w-full bg-rose-700 text-white py-2 px-4 rounded hover:bg-rose-800 transition-colors cursor-pointer"
          >
            Join
          </button>
        </form>
      </div>
    </div>
  )
}

// Presentation/src/routes/register/+page.svelte
<script>
	let email;
	let username;
	let password;

	function handleRegister() {
		// Prevent the default form submission
		event.preventDefault();

		// Perform registration logic here (e.g., API call)
		console.log('Registering:', { email, username, password });

		// Redirect to the login page after successful registration
		window.location.href = '/login';
	}
</script>

<div class="flex h-screen w-screen flex-col items-center justify-center gap-5 bg-black text-white">
	<div class="flex flex-col items-center justify-center gap-5">
		<h1 class="text-xl">No gods. No second chances, Enter if you can.</h1>
		<form class="m-0 flex flex-col gap-2 p-0" on:submit={handleRegister}>
			<p class="text-xs">Email</p>
			<input
				class="border-primary border pl-2"
				type="email"
				name="email"
				required
				bind:value={email}
			/>
			<p class="text-xs">Username</p>
			<input
				class="border-primary border pl-2"
				type="text"
				name="username"
				required
				bind:value={username}
			/>
			<p class="text-xs">Password</p>
			<input
				class="border-primary border pl-2"
				type="password"
				name="password"
				required
				bind:value={password}
			/>
			<button
				class="text-primary border-primary cursor-pointer border duration-150 hover:border-white hover:bg-white hover:text-black"
				type="submit">Register</button
			>
		</form>
	</div>
</div>
